export const authConstants = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    ADD_ADDRESS_REQUEST : "ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_SUCCESS : "ADD_ADDRESS_SUCCESS",
    ADD_ADDRESS_FAILURE : "ADD_ADDRESS_FAILURE",
    GET_ADDRESS_REQUEST : "GET_ADDRESS_REQUEST",
    GET_ADDRESS_SUCCESS : "GET_ADDRESS_SUCCESS",
    GET_ADDRESS_FAILURE : "GET_ADDRESS_FAILURE",
    
    ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST",
    ADD_ORDER_SUCCESS : "ADD_ORDER_SUCCESS",
    ADD_ORDER_FAILURE : " ADD_ORDER_FAILURE",
    GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS : "GET_ORDER_SUCCESS",
    GET_ORDER_FAILURE : " GET_ORDER_FAILURE",
    GET_ORDER_DETAILS_REQUEST: "GET_ORDER_DETAILS_REQUEST",
    GET_ORDER_DETAILS_SUCCESS : "GET_ORDER_DETAILS_SUCCESS",
    GET_ORDER_DETAILS_FAILURE : " GET_ORDER_DETAILS_FAILURE"

}
export const userConstants = {
    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_FAILURE : "USER_REGISTER_FAILURE",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
}
export const CategoryConstants ={
    GET_CATEGORY_REQUEST :"GET_CATEGORY_REQUEST",
    GET_CATEGORY_SUCCESS :"GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAILURE :"GET_CATEGORY_FAILURE",
    ADD_CATEGORY_REQUEST :"ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS :"ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE :"ADD_CATEGORY_FAILURE",
}
export const productsConstants ={
    GET_ALL_PRODUCTS_REQUEST:"GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE",
    ADD_PRODUCT_REQUEST : "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS : "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE : "ADD_PRODUCT_FAILURE",
    GET_PRODUCT_DETAILS_BY_ID_REQUEST : "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS : "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
    GET_PRODUCT_DETAILS_BY_ID_FAILURE : "GET_PRODUCT_DETAILS_BY_ID_FAILURE", 
    GET_PRODUCT_BY_SLUG_SUCCESS : "GET_PRODUCT_BY_SLUG_SUCCESS",
    GET_PRODUCT_PAGE_REQUEST : "GET_PRODUCT_PAGE_REQUEST",
    GET_PRODUCT_PAGE_SUCCESS : "GET_PRODUCT_PAGE_SUCCESS",
    GET_PRODUCT_PAGE_FAILURE : "GET_PRODUCT_PAGE_FAILURE"
}
export const initialDataConstants = {
    GET_INITIAL_DATA_REQUEST : "GET_INITIAL_DATA_REQUEST",
    GET_INITIAL_DATA_FAILURE : "GET_INITIAL_DATA_FAILURE",
    GET_INITIAL_DATA_SUCCESS : "GET_INITIAL_DATA_SUCCESS",
}
export const CartConstants = {
    ADD_TO_CART_REQUEST : "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS : "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE : "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART",
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE"
}