export const authConstants = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    

}
export const userConstants = {
    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_FAILURE : "USER_REGISTER_FAILURE",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
}
export const CategoryConstants ={
    GET_CATEGORY_REQUEST :"GET_CATEGORY_REQUEST",
    GET_CATEGORY_SUCCESS :"GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAILURE :"GET_CATEGORY_FAILURE",
    ADD_CATEGORY_REQUEST :"ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS :"ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE :"ADD_CATEGORY_FAILURE",
    UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
    UPDATE_CATEGORY_FAILURE:"UPDATE_CATEGORY_FAILURE",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_REQUEST: "DALETE_CATEGORY_REQUEST",
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_SUCCESS"
}
export const productsConstants ={
    GET_ALL_PRODUCTS_REQUEST:"GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE",
    ADD_PRODUCT_REQUEST : "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS : "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE : "ADD_PRODUCT_FAILURE"
}
export const initialDataConstants = {
    GET_INITIAL_DATA_REQUEST : "GET_INITIAL_DATA_REQUEST",
    GET_INITIAL_DATA_FAILURE : "GET_INITIAL_DATA_FAILURE",
    GET_INITIAL_DATA_SUCCESS : "GET_INITIAL_DATA_SUCCESS",
}
export const PageConstants = {
    CREATE_PAGE_REQUEST:"CREATE_PAGE_REQUEST",
    CREATE_PAGE_SUCCESS:"CREATE_PAGE_SUCCESS",
    CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE"
}